
var arrLang = {
  "en-gb": {
    "HOME": "Home",
    "FEATURE": "Feature",
    "HOW": "How We Work",
    "FAQ": "Faq",
    "LANG": "Language",
    "LANG2": "Change Language",
    "PRICELIST": "price list",
    "WA1": "Click on one of our representatives below to chat on WhatsApp",
    
    "TITLEH": "Bringing Your Vision to Life Through Logo Design",
    "DESCH": "Enhance your brand identity with a professional logo design. We are here to improve your business identity with a quality logo that suits your business needs.",
    
    "OPTION": "Logo Options",
    "FILOSOP": "Logo Philosophy",
    "LOGOS": "Derived Logo",
    "MAJOR": "Major Revision",
    "MINOR": "Minor Revisions",
    "UNLI": "Unlimited",
    "BGUID": "Branding Guidelines",
    "BMATER": "Branding Materials",
    "PKG": "Packaging Design",
    "STN": "Stationary Design",
    "MSS": "Social Media Design",
    "JSY": "Jersey Design",
    "MERCH": "Merchandise Design",
    "BCRD": "Business Card Design",
    "TWTCH": "Twitch Design Set",
    "YTUB": "Youtube Design Set",
    "FBSET": "Facebook Design Set",
    "TWTER": "Twitter Design Set",
    "FREEMOCK": "Free MockUp",
    "MASTER": "Master Files",
    "PAY": "Receive payment",
    "CTH": "Design Example",
    "CTHDESC": "The following is an example of what we have worked on.",
    
    "LOGOBRAN": "Personal Brand Logo",
    "LOGOCOMP": "Company Logo",
    "LOGOBLOG": "Blogger Logo",
    "LOGOSTAR": "StartUp Logo",
    "LOGOUMKM": "MSME Logo",
    "LOGOESPORT": "Esport Logo",
    "LOGOFREE": "Free Logo",
    "LOGOS": "Logo Design",
    
    "LINK": "Link",
    "SHOP": "Shop",
    "PORTO": "Portfolio",
    "TESTI": "Testimonials",
    "CLIENT": "Our Client",
    "SERVI": "Service",
    
    "SUPP": "Support",
    "ABOUT": "About",
    "TERM": "Terms and conditions",
    "PRIV": "Privacy Policy",
    "PROG": "Work Process",
    "HUB": "Reach Us",
    
    "HMES": "Order Now",
    "HLOG": "Your logo",
    "HBUY": "Or Just Buy It",
    "HLOGS": "Ready to Use Logo",
    "WHY": "Why",
    "HWE": "Why We Should Be Your First Choice for Logo Design",
    "HWE2": "Our logo design services are dedicated to unlocking your brand's full potential.",
    "HORI": "Original Design",
    "HORI2": "A unique logo carefully designed to make your business stand out",
    "HFAST": "Fast Process",
    "HFAST2": "We are committed to providing the best quality in an efficient time",
    "HRESP": "Quick response",
    "HRESP2": "You can rely on us, we are ready to help you 24 hours",
    "HTIME": "On time",
    "HTIME2": "We guarantee your design is completed on time, without compromising quality and creativity.",
    "HBRAND": "Start Building Your Branding Now",
    "HBRAND2": "Branding is only done once, but the benefits are many times over",
    "HPROJ": "Total Projects",
    "HCLIEN": "Happy Clients",
    "HMUST": "Must Use Professional Logo Design Services",
    "HMUST2": "Creating a good logo is not easy. You need help from professional logo design services. Here are 5 reasons why you should use professional logo design services:",
    "HUNIQ": "Get a unique logo that suits your business",
    "HUNIQ2": "Professional logo design services will conduct research on the market, competitors and your target audience before creating a logo that can highlight the advantages and value of your business",
    "HMEM": "Get an Easy to Remember Logo",
    "HMEM2": "Professional logo design services will create a logo that is simple, clear and consistent, so that it can increase your customer awareness and loyalty",
    "HCRED": "Can Increase Your Business Credibility",
    "HCRED2": "Professional logo design services will create a logo that is high quality, neat, and meets industry standards, so you can show that you are serious and competent in your business",
    "HBUDG": "According to your budget and time",
    "HBUDG2": "Professional logo design services will offer you an affordable and competitive price package, and complete your logo according to the deadline you specify, so you can save money and time.",
    "BUDG": "Rates",
    "HFLEX": "We offer a variety of flexible and affordable price options. Also get special offers that give you more value.",
    "HLAST": "Last Work",
    "HINFO": "Stay up to date on our latest work showcasing our current style and design capabilities.",
    "MUST": "Often",
    "ASK": "asked when asked",
    "FAQ0": "Frequently asked questions",
    "FAQ00": "Understand how our support team is always ready to help you & Get to know more about KangLogo.com",
    "FAQ1": "How do I order services at Kanglogo.com?",
    "FAQ1A": "Visit our website at www.kanglogo.com and select the service package you want. Or you can also place an order via WhatsApp.",
    "FAQ1B": "Fill in your logo and branding design brief completely and clearly. You can provide information about your business name, slogan, colors, style, target market, competitors and preferences.",
    "FAQ1C": "Make payment via the methods available on our website. You can use bank transfer, credit card or e-wallet.",
    "FAQ1D": "Wait for our team to work on your logo and branding design. We will send your logo and branding design concept within 1-3 working days depending on the package you choose.",
    "FAQ1E": "Provide feedback and revisions to your logo and branding design until you are satisfied with the final result. You can make free revisions according to the amount specified in the package you choose.",
    "FAQ1F": "Receive your final logo and branding design files in the format you need. You will get files in JPG, PNG, PDF, EPS, AI, and SVG formats.",
    "FAQ2A": "How long does the work process take at kanglogo.com?",
    "FAQ2B": "The work process at kanglogo.com depends on the design package you choose. Usually we include the duration of the work in each package to adjust the type of service and number of designs to be done. Usually we will send your logo and branding design concept within 1-3 working days. The work process at kanglogo.com starts after you make a payment and confirm it with us.",
    "FAQ3A": "Is there a guarantee if the design is not suitable?",
    "FAQ3B": "We provide a 100% guarantee if we have not carried out the design work due to our negligence, or we have problems with the work. We will refund your money in full if that happens. However, if the design has been worked on and the down payment has been paid, we will not provide a full refund, but we will replace the revisions as much as possible until you are satisfied with the final result. We are committed to providing the best graphic design services for you.",
    
    "JUDULLOGOBRN": "Tarif Desain Logo Personal Brand",
    "DESCLOGOBRN": "Adalah layanan jasa desain logo profesional yang diperuntukan bagi personal branding yang ingin meningkatkan brandingnya",
    
    "JUDULLOGOCOM": "Tarif Desain Logo Perusahaan",
    "DESCLOGOCOM": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    
    "JUDULLOGODGT": "Tarif Desain Logo Digital & StartUp",
    "DESCLOGODGT": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    
    "100": "USD 7$",
    "150": "USD 10$",
    "200": "USD 12$",
    "250": "USD 15$",
    "350": "USD 25$",
    "450": "USD 30$",
    "550": "USD 35$",
    "650": "USD 40",
    "700": "USD 45$",
    "800": "USD 50$",
    "850": "USD 55$",
    "950": "USD 65$",
    "1250": "USD 85$",
    "2650": "USD 170$",
    "4850": "USD 350$",
    "8850": "USD 550$",
    "FREE": "USD 0$ (FREE)"
  },

  "zh-tw": {
    "HOME": "Beranda",
    "FEATURE": "Fitur",
    "HOW": "Bagaimana Cara Kerja Kami",
    "FAQ": "Faq",
    "LANG": "Bahasa",
    "LANG2": "Ganti Bahasa",
    "PRICELIST": "Daftar Harga",
    "WA1": "Klik salah satu Admin kami di bawah ini untuk mengobrol di WhatsApp",
    
    "TITLEH": "Mewujudkan Visi Anda Melalui Desain Logo",
    "DESCH": "Tingkatkan identitas merek Anda dengan desain logo profesional. Kami hadir untuk meningkatkan identitas bisnis Anda dengan logo berkualitas dan sesuai kebutuhan bisnis anda.",
    
    "OPTION": "Opsi Logo",
    "FILOSOP": "Filosopi Logo",
    "LOGOS": "Logo Turunan",
    "MAJOR": "Revisi Besar",
    "MINOR": "Revisi Kecil",
    "UNLI": "Tidak Terbatas",
    "BGUID": "Pedoman Branding",
    "BMATER": "Material Branding",
    "PKG": "Desain Packaging",
    "STN": "Desain Stationary",
    "MSS": "Desain Media Sosial",
    "JSY": "Desain Jersey",
    "MERCH": "Desain Merchandise",
    "BCRD": "Desain Kartu Nama",
    "TWTCH": "Set Desain Twitch",
    "YTUB": "Set Desain Youtube",
    "FBSET": "Set Desain Facebook",
    "TWTER": "Set Desain Twitter",
    "FREEMOCK": "Gratis MockUp",
    "MASTER": "File Master",
    "PAY": "Menerima pembayaran",
    "CTH": "Contoh Desain",
    "CTHDESC": "Berikut ini adalah contoh yang telah kami kerjakan.",
    
    "LOGOBRAN": "Logo Personal Brand",
    "LOGOCOMP": "Logo Perusahaan",
    "LOGOBLOG": "Logo Blogger",
    "LOGOSTAR": "Logo StartUp",
    "LOGOUMKM": "Logo UMKM",
    "LOGOESPORT": "Logo Esport",
    "LOGOFREE": "Logo Gratis",
    "LOGOS": "Desain Logo",
    
    "LINK": "Tautan",
    "SHOP": "Toko",
    "PORTO": "Portofolio",
    "TESTI": "Testimonials",
    "CLIENT": "Klien Kami",
    "SERVI": "Layanan",
    
    "SUPP": "Support",
    "ABOUT": "Tentang",
    "TERM": "Syarat Ketentuan",
    "PRIV": "Kebijakan pribadi",
    "PROG": "Proses Pengerjaan",
    "HUB": "Jangkau Kami",
    
    "HMES": "Pesan Sekarang",
    "HLOG": "Logo Anda",
    "HBUY": "Atau Beli Saja",
    "HLOGS": "Logo Siap Pakai",
    "WHY": "Mengapa",
    "HWE": "Mengapa Kami Harus Menjadi Pilihan Pertama Anda untuk Desain Logo",
    "HWE2": "Layanan desain logo kami didedikasikan untuk membuka potensi penuh merek Anda.",
    "HORI": "Desain Orisinil",
    "HORI2": "Logo unik yang dirancang dengan teliti untuk membuat bisnis Anda lebih berbeda",
    "HFAST": "Proses Cepat",
    "HFAST2": "Kami berkomitmen untuk memberikan kualitas terbaik dengan waktu yang efisien",
    "HRESP": "Respon Cepat",
    "HRESP2": "Anda bisa mengandalkan kami, kami siap membantu Anda 24 jam",
    "HTIME": "Tepat Waktu",
    "HTIME2": "Kami menjamin desain Anda selesai tepat waktu, tanpa mengurangi kualitas dan kreativitas.",
    "HBRAND": "Mulailah Membangun Branding Anda Sekarang",
    "HBRAND2": "Branding hanya dibuat sekali, namun keuntungannya lebih dari berkali-kali",
    "HPROJ": "Jumlah Proyek",
    "HCLIEN": "Klien yang Bahagia",
    "HMUST": "Harus Menggunakan Jasa Desain Logo Profesional",
    "HMUST2": "Membuat logo yang baik tidaklah mudah. Anda membutuhkan bantuan dari jasa desain logo profesional. Berikut adalah 5 alasan kenapa Anda harus menggunakan jasa desain logo profesional:",
    "HUNIQ": "Mendapatkan Logo yang Unik dan Sesuai dengan Bisnis Anda",
    "HUNIQ2": "Jasa desain logo profesional akan melakukan riset tentang pasar, kompetitor, dan target audiens Anda sebelum membuat logo yang dapat menonjolkan keunggulan dan nilai bisnis Anda",
    "HMEM": "Mendapatkan Logo yang Mudah Diingat",
    "HMEM2": "Jasa desain logo profesional akan membuat logo yang sederhana, jelas, dan konsisten, sehingga dapat meningkatkan awareness dan loyalitas pelanggan Anda",
    "HCRED": "Dapat Meningkatkan Kredibilitas Bisnis Anda",
    "HCRED2": "Jasa desain logo profesional akan membuat logo yang berkualitas tinggi, rapi, dan sesuai dengan standar industri, sehingga Anda dapat menunjukkan bahwa Anda serius dan kompeten dalam bisnis Anda",
    "HBUDG": "Sesuai dengan Anggaran dan Waktu Anda",
    "HBUDG2": "Jasa desain logo profesional akan menawarkan Anda paket harga yang terjangkau dan kompetitif, serta menyelesaikan logo Anda sesuai dengan deadline yang Anda tentukan, sehingga Anda dapat menghemat biaya dan waktu Anda",
    "BUDG": "Tarif",
    "HFLEX": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    "HLAST": "Pekerjaan Terakhir",
    "HINFO": "Terus dapatkan informasi terbaru tentang karya terbaru kami yang menampilkan gaya dan kemampuan desain kami saat ini.",
    "MUST": "Sering",
    "ASK": "diajukan saat bertanya",
    "FAQ0": "Pertanyaan yang sering diajukan",
    "FAQ00": "Pahami bagaimana tim support kami selalu siap membantu Anda & Kenali lebih jauh tentang KangLogo.com",
    "FAQ1": "Bagaimana cara memesan jasa di Kanglogo.com ?",
    "FAQ1A": "Kunjungi situs web kami di www.kanglogo.com dan pilih paket layanan yang anda inginkan. Atau anda bisa juga melakukan pemesanan melalui whatsapp.",
    "FAQ1B": "Isi brief desain logo dan branding anda dengan lengkap dan jelas. Anda bisa memberikan informasi tentang nama bisnis, slogan, warna, gaya, target pasar, pesaing, dan preferensi anda.",
    "FAQ1C": "Lakukan pembayaran melalui metode yang tersedia di situs web kami. Anda bisa menggunakan transfer bank, kartu kredit, atau e-wallet.",
    "FAQ1D": "Tunggu pengerjaan desain logo dan branding anda oleh tim kami. Kami akan mengirimkan konsep desain logo dan branding anda dalam waktu 1-3 hari kerja tergantung pada paket yang anda pilih.",
    "FAQ1E": "Berikan umpan balik dan revisi untuk desain logo dan branding anda hingga anda puas dengan hasil akhirnya. Anda bisa melakukan revisi gratis sesuai dengan jumlah yang ditentukan di paket yang anda pilih.",
    "FAQ1F": "Terima file akhir desain logo dan branding anda dalam format yang anda butuhkan. Anda akan mendapatkan file dalam format JPG, PNG, PDF, EPS, AI, dan SVG.",
    "FAQ2A": "Berapa Lama Proses Kerja di kanglogo.com ?",
    "FAQ2B": "Proses kerja di kanglogo.com tergantung pada paket desain yang anda pilih. Biasanya durasi pekerjaan sudah kami cantumkan pada setiap paket guna menyesuaikan jenis layanan dan jumlah desain yang akan dikerjakan. Biasanya kami akan mengirimkan konsep desain logo dan branding anda dalam waktu 1-3 hari kerja. Proses kerja di kanglogo.com dimulai setelah anda melakukan pembayaran dan mengkonfirmasinya kepada kami.",
    "FAQ3A": "Apakah bergaransi jika desain kurang sesuai ?",
    "FAQ3B": "Kami memberikan garansi 100% jika pengerjaan desain belum kami lakukan disebabkan kelalaian kami, atau kami memiliki kendala dalam pengerjaan. Kami akan mengembalikan uang anda sepenuhnya jika itu terjadi. Namun, jika desain sudah dikerjakan dan uang muka dibayarkan, kami tidak memberikan penggantian uang sepenuhnya, namun kami akan mengganti revisi sepuasnya hingga anda puas dengan hasil akhirnya. Kami berkomitmen untuk memberikan layanan desain grafis terbaik untuk anda.",
    
    "JUDULLOGOBRN": "Tarif Desain Logo Personal Brand",
    "DESCLOGOBRN": "Adalah layanan jasa desain logo profesional yang diperuntukan bagi personal branding yang ingin meningkatkan brandingnya",
    
    "JUDULLOGOCOM": "Tarif Desain Logo Perusahaan",
    "DESCLOGOCOM": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    
    "JUDULLOGODGT": "Tarif Desain Logo Digital & StartUp",
    "DESCLOGODGT": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    
    "100": "Rp 100.000",
    "150": "Rp 150.000",
    "200": "Rp 200.000",
    "250": "Rp 250.000",
    "350": "Rp 350.000",
    "450": "Rp 450.000",
    "550": "Rp 550.000",
    "650": "Rp 650.000",
    "700": "Rp 700.000",
    "800": "Rp 800.000",
    "850": "Rp 850.000",
    "950": "Rp 950.000",
    "1250": "Rp 1.250.000",
    "2650": "Rp 2.650.000",
    "4850": "Rp 4.850.000",
    "8850": "Rp 8.550.000",
    "FREE": "Rp 0 (GRATIS)"
  }
    };



 $(document).ready(function () {
      var lang = localStorage.getItem('lang') || 'en-gb';
      $(".lang").each(function (index, element) {
        $(this).text(arrLang[lang][$(this).attr("key")]);
      });

      $(".translate").click(function () {
        var lang = $(this).attr("id");
        localStorage.setItem('lang', lang);

        $(".lang").each(function (index, element) {
          $(this).text(arrLang[lang][$(this).attr("key")]);
        });
      });
    });
