
var arrLang = {
  "en-gb": {
    "HOME": "Home",
    "FEATURE": "Feature",
    "HOW": "How We Work",
    "FAQ": "Faq",
    "LANG": "Language",
    "LANG2": "Change Language",
    "PRICELIST": "price list",
    "WA1": "Click on one of our representatives below to chat on WhatsApp",
    "WA2": "Need help? Let's chat with us!",
    "WA3": "Hello! What can I do for you?",
    
    "TITLEH": "Bringing Your Vision to Life Through Logo Design",
    "DESCH": "Enhance your brand identity with a professional logo design. We are here to improve your business identity with a quality logo that suits your business needs.",
    
    "OPTION": "Logo Options",
    "FILOSOP": "Logo Philosophy",
    "LOGOS": "Derived Logo",
    "MAJOR": "Major Revision",
    "MINOR": "Minor Revisions",
    "UNLI": "Unlimited",
    "BGUID": "Branding Guidelines",
    "BMATER": "Branding Materials",
    "PKG": "Packaging Design",
    "STN": "Stationary Design",
    "MSS": "Social Media Design",
    "JSY": "Jersey Design",
    "MERCH": "Merchandise Design",
    "BCRD": "Business Card Design",
    "TWTCH": "Twitch Design Set",
    "YTUB": "Youtube Design Set",
    "FBSET": "Facebook Design Set",
    "TWTER": "Twitter Design Set",
    "FREEMOCK": "Free MockUp",
    "MASTER": "Master Files",
    "PAY": "Receive payment",
    "CTH": "Design Example",
    "CTHDESC": "The following is an example of what we have worked on.",
    
    "LOGOBRAN": "Personal Brand Logo",
    "LOGOCOMP": "Company Logo",
    "LOGOBLOG": "Blogger Logo",
    "LOGOSTAR": "StartUp Logo",
    "LOGOUMKM": "MSME Logo",
    "LOGOESPORT": "Esport Logo",
    "LOGOFREE": "Free Logo",
    "LOGOS": "Logo Design",
    
    "LINK": "Link",
    "SHOP": "Shop",
    "PORTO": "Portfolio",
    "TESTI": "Testimonials",
    "CLIENT": "Our Client",
    "SERVI": "Service",
    
    "SUPP": "Support",
    "ABOUT": "About",
    "TERM": "Terms and conditions",
    "PRIV": "Privacy Policy",
    "PROG": "Work Process",
    "HUB": "Reach Us",
    "VSI": "Vision",
    "MSI": "Mission",
    "TGT": "Our Target",
    "STTG": "Our strategy",
    "KDSN": "Design Type",
    "SRVDS": "Design service",
    "CLFM": "Color and File Format",
    "DTBRF": "Data Briefing",
    "CHGBRF": "Change Data Briefing",
    "UPKG": "Upgrade Package",
    "DDLN": "Project Completion Timeframe",
    "FINL": "End Results or Completion of Services",
    "CPYBRD": "Copyright and Trademark",
    "USDSGN": "Design Use for Promotional Media",
    "USPKG": "Use of Non-Source File Design Packages",
    "USCOM": "Using Design for Commercial Products",
    "PAYFL": "Full Payment",
    "PAYDW": "Down Payment",
    "RFND": "Refund or Money-Back Guarantee",
    "CNFRM": "Payment Confirmation",
    "INFRM1": "What information do we collect?",
    "INFRM2": "How do we utilize this information?",
    "INFRM3": "How do we safeguard your information?",
    "INFRM4": "Do we share your information with third parties?",
    "INFRM5": "How can you access or update your information?",
    "INFRM6": "Do we use cookies?",
    "IDSU": "General Industry",
    "IDST": "Technology Industry",
    "TKOU": "Online Store / MSME",
    
    "HMES": "Order Now",
    "HLOG": "Your logo",
    "HBUY": "Or Just Buy It",
    "HLOGS": "Ready to Use Logo",
    "WHY": "Why",
    "HWE": "Why We Should Be Your First Choice for Logo Design",
    "HWE2": "Our logo design services are dedicated to unlocking your brand's full potential.",
    "HORI": "Original Design",
    "HORI2": "A unique logo carefully designed to make your business stand out",
    "HFAST": "Fast Process",
    "HFAST2": "We are committed to providing the best quality in an efficient time",
    "HRESP": "Quick response",
    "HRESP2": "You can rely on us, we are ready to help you 24 hours",
    "HTIME": "On time",
    "HTIME2": "We guarantee your design is completed on time, without compromising quality and creativity.",
    "HBRAND": "Start Building Your Branding Now",
    "HBRAND2": "Branding is only done once, but the benefits are many times over",
    "HPROJ": "Total Projects",
    "HCLIEN": "Happy Clients",
    "HMUST": "Must Use Professional Logo Design Services",
    "HMUST2": "Creating a good logo is not easy. You need help from professional logo design services. Here are 5 reasons why you should use professional logo design services:",
    "HUNIQ": "Get a unique logo that suits your business",
    "HUNIQ2": "Professional logo design services will conduct research on the market, competitors and your target audience before creating a logo that can highlight the advantages and value of your business",
    "HMEM": "Get an Easy to Remember Logo",
    "HMEM2": "Professional logo design services will create a logo that is simple, clear and consistent, so that it can increase your customer awareness and loyalty",
    "HCRED": "Can Increase Your Business Credibility",
    "HCRED2": "Professional logo design services will create a logo that is high quality, neat, and meets industry standards, so you can show that you are serious and competent in your business",
    "HBUDG": "According to your budget and time",
    "HBUDG2": "Professional logo design services will offer you an affordable and competitive price package, and complete your logo according to the deadline you specify, so you can save money and time.",
    "BUDG": "Rates",
    "HFLEX": "We offer a variety of flexible and affordable price options. Also get special offers that give you more value.",
    "HLAST": "Last Work",
    "HINFO": "Stay up to date on our latest work showcasing our current style and design capabilities.",
    "MUST": "Often",
    "ASK": "asked when asked",
    "FAQ0": "Frequently asked questions",
    "FAQ00": "Understand how our support team is always ready to help you & Get to know more about KangLogo.com",
    "FAQ1": "How do I order services at Kanglogo.com?",
    "FAQ1A": "Visit our website at www.kanglogo.com and select the service package you want. Or you can also place an order via WhatsApp.",
    "FAQ1B": "Fill in your logo and branding design brief completely and clearly. You can provide information about your business name, slogan, colors, style, target market, competitors and preferences.",
    "FAQ1C": "Make payment via the methods available on our website. You can use bank transfer, credit card or e-wallet.",
    "FAQ1D": "Wait for our team to work on your logo and branding design. We will send your logo and branding design concept within 1-3 working days depending on the package you choose.",
    "FAQ1E": "Provide feedback and revisions to your logo and branding design until you are satisfied with the final result. You can make free revisions according to the amount specified in the package you choose.",
    "FAQ1F": "Receive your final logo and branding design files in the format you need. You will get files in JPG, PNG, PDF, EPS, AI, and SVG formats.",
    "FAQ2A": "How long does the work process take at kanglogo.com?",
    "FAQ2B": "The work process at kanglogo.com depends on the design package you choose. Usually we include the duration of the work in each package to adjust the type of service and number of designs to be done. Usually we will send your logo and branding design concept within 1-3 working days. The work process at kanglogo.com starts after you make a payment and confirm it with us.",
    "FAQ3A": "Is there a guarantee if the design is not suitable?",
    "FAQ3B": "We provide a 100% guarantee if we have not carried out the design work due to our negligence, or we have problems with the work. We will refund your money in full if that happens. However, if the design has been worked on and the down payment has been paid, we will not provide a full refund, but we will replace the revisions as much as possible until you are satisfied with the final result. We are committed to providing the best graphic design services for you.",
    "ABOUT1": "Who are we?",
    "ABOUT2": "Kanglogo.com is a professional service provider in creating logos, banners, icons, illustrations, and other graphic designs. Established in 2021, we have served thousands of clients from domestic and international markets who have entrusted us with their logo and branding design needs. We serve various types of businesses, ranging from micro, small, and medium enterprises to personal websites. Our focus is to provide the best quality service to meet your graphic design needs. We have a creative and experienced team to produce logo and branding designs that suit your business identity. By choosing Kanglogo.com, you will get the best graphic design services to enhance your business image.",
    "ABOUT3": "What makes Kanglogo.com different from other graphic design service providers? Here are some reasons why you should choose Kanglogo.com:",
    "ABOUT4": "We offer affordable and transparent prices for every service we offer. You can see our price list on our website and choose a package that suits your budget and needs.",
    "ABOUT5": "We offer an easy and fast process to get the logo and branding design you want. You only need to fill out the brief, make a payment, wait for the design work, give feedback, and receive the final file.",
    "ABOUT6": "We offer a satisfaction guarantee and free revisions for every service we offer. You can give feedback and suggestions to improve your logo and branding design until you are satisfied with the final result.",
    "ABOUT7": "We offer free consultation services to help you determine the concept and style of logo and branding design that suits your business. You can contact us via email, phone, or online chat anytime you need assistance or advice.",
    "ABOUT8": "We offer a wide and quality portfolio to showcase our ability and experience in graphic design. You can see examples of logo and branding designs that we have made for our previous clients on our website.",
    "ABOUT9": "To become a trusted design company recognized by our clients for the quality of service and creativity we provide.",
    "ABOUT10": "To become a design company that not only provides design services, but also able to provide positive impact for companies that use our services.",
    "ABOUT11": "To become a design company in Indonesia that is committed to bringing about change that is not only service-oriented, but also beneficial for religious, humanitarian, and social organizations that require our support.",
    "ABOUT12": "To build strong relationships with our clients and service partners to foster trust and produce the best possible work.",
    "ABOUT13": "To continuously improve the skills and expertise of our design team to deliver creative and innovative results in every project we undertake.",
    "ABOUT14": "We use design software that is easily accessible by clients, making it easy for them to receive and modify the design files we provide. In addition, we are committed to using legal design software and assets, without engaging in piracy or illegal use of design assets. Thus, we can provide safe, accurate, and high-quality design solutions for our clients.",
    "ABOUT15": "Creating a healthy and productive work environment for our design team, and motivating them to continue to develop and provide the best for our clients.",
    "ABOUT16": "We are committed to maintaining our commitment to sustainability and responsibility in every aspect of our business activities, including minimizing negative impacts on the environment and surrounding communities.",
    "ABOUT17": "Our target customers are businesses in the range of micro, small, and medium enterprises, and individuals looking for professional logo design services. We believe that by providing high-quality design services, we can help improve the image and public trust of these businesses or individuals. We focus on understanding the needs and preferences of our clients by actively listening to their requests and feedback. In addition, we ensure that the designs we produce not only have high aesthetic value but also accurately represent the values and goals of the businesses or individuals we serve. We are committed to providing timely, effective, and efficient design solutions. We are ready to collaborate with our clients at every stage of the design process, from planning and conceptualization to design implementation.",
    "ABOUT18": "Our strategy is to offer professional, unique, and attractive logo design services at affordable and competitive prices. We want to be the top choice for our clients in meeting their logo design needs. We use digital marketing strategies to reach and attract potential customers. We utilize our website, social media, email, and blog to promote our services and showcase our portfolio. We also use testimonials, reviews, and references from our previous clients to enhance our credibility and reputation. We use friendly, responsive, and transparent customer service strategies to maintain and improve customer loyalty. We strive to provide the best experience for our clients throughout the logo design process. We are always ready to answer questions, provide advice, and resolve any issues that may arise. We also provide a satisfaction guarantee and free revisions for every service we offer.",
    "ABOUT19": "Types of designs we use: We use various types of designs to create logos that are suitable for the identity and message of the businesses or individuals we serve. The types of designs we use include:",
    "ABOUT20": "Minimalist design: This design uses simple, clean, and functional elements to create a logo that is easy to remember and elegant. This design is suitable for businesses or individuals who want to show professionalism, quality, and simplicity.",
    "ABOUT21": "Character design: This design uses characters, whether human, animal, or object, to create a logo that is attractive and fun. This design is suitable for businesses or individuals who want to show personality, creativity, and uniqueness.",
    "ABOUT22": "Elegant design: This design uses luxurious, graceful, and classic elements to create a logo that is classy and prestigious. This design is suitable for businesses or individuals who want to show luxury, elegance, and sophistication.",
    "ABOUT23": "Flat design: This design uses flat, simple, and colorful elements to create a modern and dynamic logo. This design is suitable for businesses or individuals who want to show contemporaneity, innovation, and freshness.",
    "ABOUT24": "We also always support new design updates that are currently trending. We always follow the developments and changes in the world of graphic design. We always strive to produce logo designs that are relevant, up-to-date, and stand out among competitors.",
    "ABOUT25": "Kanglogo.com is the best choice for your logo and branding design needs. With Kanglogo.com, you will get professional, unique, and attractive logo and branding designs to represent your business. Contact us and order our services now!",
    "ABOUT26": "If you have any questions about our services and business information, please contact us via email at kanglogokece@gmail.com. We will be happy to answer your questions and provide the information you need. You can also visit our website at www.kanglogo.com to see more about our services and portfolio. We hope to work with you in realizing your dream logo and branding. Thank you for your interest and trust in Kanglogo.com.",
    "TERM1": "Before using Kanglogo.com’s design services, it is important for you to read and understand the terms and conditions, design creation procedures, and FAQs on this page. These terms and conditions may change at any time without prior notice, and by using Kanglogo.com’s services, you are deemed to agree to and be bound by such changes. Therefore, we recommend that you regularly check and understand the contents of these terms and conditions and any changes to them. You are responsible for knowing and complying with the applicable terms and conditions to avoid problems later on.",
    "TERM2": "The design services provided by Kanglogo.com offer online design services aimed at individuals or companies through websites and social media without the need for face-to-face meetings. After placing an order through the available form and completing full payment and payment confirmation, clients can send specific project briefings in the form of written text and reference images, as well as revise received designs.",
    "TERM3": "Kanglogo.com provides various design services described in each package listed in brochures or selected websites, in accordance with established procedures. Changes to design package specifications only apply to orders after such changes, and cannot be applied retrospectively.",
    "TERM4": "The color standard used in every design project is RGB, unless the client requests another color standard such as PANTONE or CMYK. If there are changes to the color standard after the project has started, additional fees will be charged. Similarly, requesting two color standards in the final result will also incur additional fees.",
    "TERM5": "The file formats provided include soft files such as PNG/JPG and source files such as EPS/AI/CDR/PDF/PSD. Acceptance of file formats is adjusted to the selected package and cannot be changed under certain conditions. If the client requests or adds other file formats that are not listed in the package, additional fees will be charged.",
    "TERM6": "The client is fully responsible for writing briefing data and conducting the necessary research for design projects, including presenting research results clearly, consistently, and accurately, as well as presenting adequate references and illustrations or relevant images related to the sent briefing. Briefing data must be sent in text form along with adequate reference files via forms, chat messages, email, or social media.",
    "TERM7": "Kanglogo.com is not responsible for reviewing or correcting the content of the sent briefing. If there are changes to the briefing data, changes must be made in the same way when sending the briefing and before the design process begins.",
    "TERM8": "We cannot accept briefings delivered orally or in easily erasable media, as they are considered not sent or not received by us as a service provider.",
    "TERM9": "Changes to briefing data after the work process is considered a revision. The number of revisions allowed will be adjusted to the selected package and additional revisions will incur additional fees. We recommend that clients map changes and collect all changes in one revision to reduce excessive revisions.",
    "TERM10": "We will calculate revision costs based on requested changes. If there are errors in delivering briefings, revisions will be considered changes and will be reduced according to the number of requested changes.",
    "TERM11": "We would also like to remind you that revisions will be stopped if they exceed the normal limit provided in the selected package, so we recommend that clients consider carefully before requesting additional revisions.",
    "TERM12": "To avoid repeated revisions and ensure customer satisfaction, after revisions are complete, we request additional briefings and references as the main reference to understand the type and design preferences of the desired logo. If you cannot provide a briefing within 3 days after the revision is complete, then we cannot continue the work and cannot provide a refund. Therefore, we strongly recommend that you provide clear and timely briefings so that the project can be completed successfully.",
    "TERM13": "Kanglogo.com is committed to providing fast, timely, and flexible responses, communication, and flexibility to our clients. We are ready to respond and answer your questions before and during the design process. We ask our clients to also respond to every message or question we ask, especially regarding briefing data needed to start the design process.",
    "TERM14": "We highly recommend that clients respond to every message we send to avoid misunderstandings and lack of information needed to complete the design well. We will pay attention to every response and question you ask, and will take necessary action to ensure that the design we send is in accordance with your needs and desires.",
    "TERM15": "However, if clients do not respond to our messages or questions within a specified period of time, we are not responsible for errors in design results due to lack of or errors in briefing designs that we receive. We ask clients to pay attention to every message and question we ask to avoid errors.",
    "TERM16": "If we do not receive a response from the client within a certain period of time after sending the design results, we will postpone the work for 1 week. If after 1 week there is no response from the client, we will send the file format according to the package ordered and the work is considered complete. We expect good cooperation and communication from clients so that we can provide satisfactory design results.",
    "TERM17": "We offer options to upgrade service packages that have been ordered by clients, both at the pre-design stage or after the design process is complete. We provide flexibility within two weeks after the design file has been sent to clients. During this period, clients can upgrade service packages according to emerging needs. We are ready to provide advice and guidance to clients regarding available upgrade options. However, after the two-week period ends, we cannot accept requests to upgrade service packages.",
    "TERM18": "We have a standard project completion period listed in each service package we offer. We are committed to completing projects within the specified time frame, which is 3 working days (4 days if working days coincide with holidays or holidays) after payment and briefing delivery. We expect quick and timely responses from clients regarding the design results we send, so that work can be completed on time.",
    "TERM19": "If clients do not respond to the design results we send within 14 days after delivery, then on the 15th day we will send the design results without any review from clients. In this case, cooperation between Kanglogo.com and clients is considered complete and we no longer have an obligation to work on projects. We also will not refund payments made by clients, without exception.",
    "TERM20": "The client has full rights to the final result of one design that we make. However, the client does not have the right to all revisions and/or initial concepts, as well as derivative products. Therefore, clients are not allowed to forward, display, or publish revisions and/or initial concepts to any party, anywhere, and through any media.",
    "TERM21": "We need to emphasize that if clients violate these provisions, Kanglogo.com Studio has the right to stop any type of service or product that we provide to clients without any compensation in any form. We sincerely hope that clients can respect our copyright and privacy, as we respect clients as our customers.",
    "TERM22": "We guarantee that the designs we create are original and we can prove it through sketches or our work on paper. After the design is approved or purchased by the client, copyright and patent rights to the design will be fully owned by the client. However, it should be noted that the design that is the client’s copyright is the final design that has been approved, whether it has been revised or not. Initial designs or designs not selected by clients will remain ours and we have the right to sell or reuse them as our assets. After delivering the design and license documents to clients, clients will become official owners of copyright and patent rights to approved or purchased designs.",
    "TERM23": "Kanglogo.com has full rights to use final designs that have been approved by clients as a means of promotion on our portfolio website and social media without additional fees or royalties (royalty-free) with a time limit for unlimited use.",
    "TERM24": "If the client uses a non-source file package service and wants to use the design for print media, the client must purchase source files at the following prices: Rp 250,000 for Ai or CDR files, Rp 300,000 for PSD files, and Rp 500,000 for double source files such as AI, CDR, PSD, PDF, EPS, and SVG.",
    "TERM25": "We want to inform you that as a client, you have copyright to approved or purchased designs, and you can use them for commercial purposes or distribution as desired. However, you must comply with copyright rules and not violate them such as vectorizing design software files in other services without permission from the copyright owner.",
    "TERM26": "If there is a copyright violation or unauthorized use of the design, we will take legal action necessary to enforce our or clients’ copyright as the owner of the design. As a design service provider, we respect copyrights and prohibit all forms of violations.",
    "TERM27": "For every transaction with an amount below Rp 300,000 (Three Hundred Thousand Rupiah), clients are required to make full payment before the project can begin.",
    "TERM28": "As a standard payment procedure, we require clients to make a down payment of 40% if the total transaction amount is above Rp 301,000 before starting the project.",
    "TERM29": "If the client is not satisfied with the initial concept we provide and has not requested a revision, they can request a refund for the payment made. However, this only applies to transactions that have not been paid in full. If the service fee is paid in cash, a refund of 70% of the transaction amount will be given. Meanwhile, if the service fee is paid as a down payment, a refund of 60% of the transaction amount will be given. However, clients are not entitled to a refund if they have requested revisions or failed to respond within the specified period.",
    "TERM30": "To mark the start of the service work process, clients are required to confirm payment by sending a photo of proof of payment or screenshot as proof of payment. We will upload this screenshot as a testimonial from clients on our social media or website. To maintain client privacy, names and account numbers will be obscured.",
    "PRIV1": "We highly respect our users’ privacy and strive to maintain the personal information they provide us through our services. This privacy policy explains how we collect, use, and maintain our users’ personal information.",
    "PRIV2": "We collect information that you provide to us when you use our services, such as your full name, email address, phone number, and payment information.",
    "PRIV3": "We use the personal information we collect for specific purposes, such as completing orders, sending order-related emails, and providing customer support. We may also use this information to send promotions and special offers related to our services, but you can always choose not to receive these emails.",
    "PRIV4": "We take appropriate security measures to protect your personal information from unauthorized access or use. We also use SSL encryption to protect your personal information when transmitted over the internet.",
    "PRIV5": "We do not sell, trade, or rent our users’ personal information to third parties. However, we may share your information with third parties if necessary to complete payment or to comply with applicable laws or legal processes.",
    "PRIV6": "You can request access to your personal information that we store or update that information by contacting us via email or phone number listed below.",
    "PRIV7": "Yes, we use cookies to track user preferences and to enhance the user experience on our website.",
    "PRIV8": "This policy may change from time to time. Any changes to this policy will be posted on our website. If you have any questions or comments about our privacy policy, please contact us via email at kanglogokece@gmail.com or by phone at +62 818-145-012.",
    "PROG1": "Design Process: From Start to Finish",
    "PROG2": "We have a professional and creative design process, consisting of seven different steps, from client briefing to delivery and branding guidelines.",
    "PROG3": "The design process includes seven systematic and structured steps",
    "PROG4": "Starting from client briefing to delivery and branding guidelines. We communicate, collaborate, and innovate to provide the best logo design solutions for your business.",
    "PROG5": "Client Briefing",
    "PROG6": "We communicate with clients to understand their needs, goals, and expectations. We also collect information about businesses, their target markets, competitors, and style preferences.",
    "PROG7": "Research and Inspiration",
    "PROG8": "We conduct research on industries, trends, and design examples relevant to design projects. We also seek inspiration from creative sources such as art, culture, or nature.",
    "PROG9": "Concept Development",
    "PROG10": "We started developing a design concept based on the results of briefings and research. We create sketches, mood boards, or mockups to visually explore design ideas.",
    "PROG11": "Design Refinements",
    "PROG12": "We chose the best design concept and began to perfect it. We pay attention to details, colors, typography, and other elements that affect the aesthetics and function of those designs.",
    "PROG13": "Presentation",
    "PROG14": "We present the design to the client and explain the reasoning and process behind it. We also get feedback from clients and evaluate the strengths and weaknesses of the design.",
    "PROG15": "Revision and Approval",
    "PROG16": "We made design revisions according to client feedback. We also ensure that the design meets the required quality standards and technical specifications. We get the final approval from the client before proceeding to the final step.",
    "PROG17": "Shipping and Branding Guide",
    "PROG18": "We prepare and deliver the design file to the client in the appropriate format. We also provide usage and branding guidelines for designs so that clients can use them correctly and consistently",
    "ORIG": "Original Design",
    "CUSTCOL": "Customized color",
    "CUSTEXT": "Customized text",
    "EDMF": "Editable Master Files",
    "LCNS": "Use License",
    "ATCRT": "Add To Cart",
    "ORDR": "Order Now",
    "DESCRP": "Description",
    
    "JUDULKLIEN": "Our Best Client",
    "DESCKLIEN1": "Here you can see our best clients from various fields and sectors. We always try to provide the best, appropriate, and satisfying services for them.",
    "DESCKLIEN2": "We are proud to have the best clients who have chosen our logo design services.",
    "JUDULTSTMN": "Customer Testimonials",
    "DESCTSTMN1": "We are proud of our work and we are happy to see our customers satisfied with our logo design services.",
    "DESCTSTMN2": "What do our customers say about our logo design services?",
    "JUDULLOGOBRN": "Personal Brand Logo Design Rates",
    "DESCLOGOBRN": "Is a professional logo design service intended for personal branding who wants to improve their branding",
    "JUDULLOGOCOM": "Corporate Logo Design Rates",
    "DESCLOGOCOM": "Is a professional logo design service for companies, be it small or large scale companies.",
    "JUDULLOGODGT": "Digital & StartUp Logo Design Rates",
    "DESCLOGODGT": "Is a professional logo design service intended for startups, digital companies, online stores, ecourse, ecomerce and others.",
    "JUDULLOGOBLG": "Blog Logo Design Rates",
    "DESCLOGOBLG": "Is a professional logo design service intended for blog users, be it personal blogs, news blogs and others.",
    "JUDULLOGOEVN": "Event or organization logo design rates",
    "DESCLOGOEVN": "Is a professional logo design service intended for a symbol of an event, birthday, commemoration and others.",
    "JUDULLOGOESP": "Esport Logo Design Rates",
    "DESCLOGOESP": "Is a professional logo design service intended for beginner or professional streamers",
    "JUDULLOGOUMK": "MSME Logo Design Rates",
    "DESCLOGOUMK": "Is a professional logo design service intended for MSME business",
    
    "100": "USD 7$",
    "150": "USD 10$",
    "200": "USD 12$",
    "250": "USD 15$",
    "350": "USD 25$",
    "450": "USD 30$",
    "550": "USD 35$",
    "650": "USD 40",
    "700": "USD 45$",
    "800": "USD 50$",
    "850": "USD 55$",
    "950": "USD 65$",
    "1250": "USD 85$",
    "2650": "USD 170$",
    "4850": "USD 350$",
    "8850": "USD 550$",
    "FREE": "USD 0$ (FREE)"
  },

  "zh-tw": {
    "HOME": "Beranda",
    "FEATURE": "Fitur",
    "HOW": "Bagaimana Cara Kerja Kami",
    "FAQ": "Faq",
    "LANG": "Bahasa",
    "LANG2": "Ganti Bahasa",
    "PRICELIST": "Daftar Harga",
    "WA1": "Klik salah satu Admin kami di bawah ini untuk mengobrol di WhatsApp",
    "WA2": "Butuh bantuan? Mari ngobrol dengan kami!",
    "WA3": "Halo! Apa ada yang bisa saya bantu?",
    
    "TITLEH": "Mewujudkan Visi Anda Melalui Desain Logo",
    "DESCH": "Tingkatkan identitas merek Anda dengan desain logo profesional. Kami hadir untuk meningkatkan identitas bisnis Anda dengan logo berkualitas dan sesuai kebutuhan bisnis anda.",
    
    "OPTION": "Opsi Logo",
    "FILOSOP": "Filosopi Logo",
    "LOGOS": "Logo Turunan",
    "MAJOR": "Revisi Besar",
    "MINOR": "Revisi Kecil",
    "UNLI": "Tidak Terbatas",
    "BGUID": "Pedoman Branding",
    "BMATER": "Material Branding",
    "PKG": "Desain Packaging",
    "STN": "Desain Stationary",
    "MSS": "Desain Media Sosial",
    "JSY": "Desain Jersey",
    "MERCH": "Desain Merchandise",
    "BCRD": "Desain Kartu Nama",
    "TWTCH": "Set Desain Twitch",
    "YTUB": "Set Desain Youtube",
    "FBSET": "Set Desain Facebook",
    "TWTER": "Set Desain Twitter",
    "FREEMOCK": "Gratis MockUp",
    "MASTER": "File Master",
    "PAY": "Menerima pembayaran",
    "CTH": "Contoh Desain",
    "CTHDESC": "Berikut ini adalah contoh yang telah kami kerjakan.",
    
    "LOGOBRAN": "Logo Personal Brand",
    "LOGOCOMP": "Logo Perusahaan",
    "LOGOBLOG": "Logo Blogger",
    "LOGOSTAR": "Logo StartUp",
    "LOGOUMKM": "Logo UMKM",
    "LOGOESPORT": "Logo Esport",
    "LOGOFREE": "Logo Gratis",
    "LOGOS": "Desain Logo",
    
    "LINK": "Tautan",
    "SHOP": "Toko",
    "PORTO": "Portofolio",
    "TESTI": "Testimonials",
    "CLIENT": "Klien Kami",
    "SERVI": "Layanan",
    
    "SUPP": "Support",
    "ABOUT": "Tentang",
    "TERM": "Syarat Ketentuan",
    "PRIV": "Kebijakan pribadi",
    "PROG": "Proses Pengerjaan",
    "HUB": "Jangkau Kami",
    "VSI": "Visi",
    "MSI": "Misi",
    "TGT": "Target Kami",
    "STTG": "Strategi kami",
    "KDSN": "Jenis Desain",
    "SRVDS": "Layanan desain",
    "CLFM": "Warna dan Format File",
    "DTBRF": "Data Briefing",
    "CHGBRF": "Perubahan Data Briefing",
    "UPKG": "Upgrade Paket",
    "DDLN": "Jangka Waktu Penyelesaian Proyek",
    "FINL": "Hasil Akhir atau Penyelesaian Layanan",
    "CPYBRD": "Hak Cipta dan Merek Dagang",
    "USDSGN": "Penggunaan Desain untuk Media Promosi",
    "USPKG": "Penggunaan Paket Desain Non-File Sumber",
    "USCOM": "Menggunakan Desain untuk Produk Komersial",
    "PAYFL": "Pembayaran Penuh",
    "PAYDW": "Pembayaran Uang Muka",
    "RFND": "Pengembalian Dana atau Jaminan Uang Kembali",
    "CNFRM": "Konfirmasi Pembayaran",
    "INFRM1": "Informasi apa yang kami kumpulkan?",
    "INFRM2": "Bagaimana kami memanfaatkan informasi ini?",
    "INFRM3": "Bagaimana kami menjaga informasi Anda?",
    "INFRM4": "Apakah kami membagikan informasi Anda dengan pihak ketiga?",
    "INFRM5": "Bagaimana Anda dapat mengakses atau memperbarui informasi Anda?",
    "INFRM6": "Apakah kami menggunakan cookie?",
    "IDSU": "Industri Umum",
    "IDST": "Industri Teknologi",
    "TKOU": "Toko Online / UMKM",
    
    "HMES": "Pesan Sekarang",
    "HLOG": "Logo Anda",
    "HBUY": "Atau Beli Saja",
    "HLOGS": "Logo Siap Pakai",
    "WHY": "Mengapa",
    "HWE": "Mengapa Kami Harus Menjadi Pilihan Pertama Anda untuk Desain Logo",
    "HWE2": "Layanan desain logo kami didedikasikan untuk membuka potensi penuh merek Anda.",
    "HORI": "Desain Orisinil",
    "HORI2": "Logo unik yang dirancang dengan teliti untuk membuat bisnis Anda lebih berbeda",
    "HFAST": "Proses Cepat",
    "HFAST2": "Kami berkomitmen untuk memberikan kualitas terbaik dengan waktu yang efisien",
    "HRESP": "Respon Cepat",
    "HRESP2": "Anda bisa mengandalkan kami, kami siap membantu Anda 24 jam",
    "HTIME": "Tepat Waktu",
    "HTIME2": "Kami menjamin desain Anda selesai tepat waktu, tanpa mengurangi kualitas dan kreativitas.",
    "HBRAND": "Mulailah Membangun Branding Anda Sekarang",
    "HBRAND2": "Branding hanya dibuat sekali, namun keuntungannya lebih dari berkali-kali",
    "HPROJ": "Jumlah Proyek",
    "HCLIEN": "Klien yang Bahagia",
    "HMUST": "Harus Menggunakan Jasa Desain Logo Profesional",
    "HMUST2": "Membuat logo yang baik tidaklah mudah. Anda membutuhkan bantuan dari jasa desain logo profesional. Berikut adalah 5 alasan kenapa Anda harus menggunakan jasa desain logo profesional:",
    "HUNIQ": "Mendapatkan Logo yang Unik dan Sesuai dengan Bisnis Anda",
    "HUNIQ2": "Jasa desain logo profesional akan melakukan riset tentang pasar, kompetitor, dan target audiens Anda sebelum membuat logo yang dapat menonjolkan keunggulan dan nilai bisnis Anda",
    "HMEM": "Mendapatkan Logo yang Mudah Diingat",
    "HMEM2": "Jasa desain logo profesional akan membuat logo yang sederhana, jelas, dan konsisten, sehingga dapat meningkatkan awareness dan loyalitas pelanggan Anda",
    "HCRED": "Dapat Meningkatkan Kredibilitas Bisnis Anda",
    "HCRED2": "Jasa desain logo profesional akan membuat logo yang berkualitas tinggi, rapi, dan sesuai dengan standar industri, sehingga Anda dapat menunjukkan bahwa Anda serius dan kompeten dalam bisnis Anda",
    "HBUDG": "Sesuai dengan Anggaran dan Waktu Anda",
    "HBUDG2": "Jasa desain logo profesional akan menawarkan Anda paket harga yang terjangkau dan kompetitif, serta menyelesaikan logo Anda sesuai dengan deadline yang Anda tentukan, sehingga Anda dapat menghemat biaya dan waktu Anda",
    "BUDG": "Tarif",
    "HFLEX": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    "HLAST": "Pekerjaan Terakhir",
    "HINFO": "Terus dapatkan informasi terbaru tentang karya terbaru kami yang menampilkan gaya dan kemampuan desain kami saat ini.",
    "MUST": "Sering",
    "ASK": "diajukan saat bertanya",
    "FAQ0": "Pertanyaan yang sering diajukan",
    "FAQ00": "Pahami bagaimana tim support kami selalu siap membantu Anda & Kenali lebih jauh tentang KangLogo.com",
    "FAQ1": "Bagaimana cara memesan jasa di Kanglogo.com ?",
    "FAQ1A": "Kunjungi situs web kami di www.kanglogo.com dan pilih paket layanan yang anda inginkan. Atau anda bisa juga melakukan pemesanan melalui whatsapp.",
    "FAQ1B": "Isi brief desain logo dan branding anda dengan lengkap dan jelas. Anda bisa memberikan informasi tentang nama bisnis, slogan, warna, gaya, target pasar, pesaing, dan preferensi anda.",
    "FAQ1C": "Lakukan pembayaran melalui metode yang tersedia di situs web kami. Anda bisa menggunakan transfer bank, kartu kredit, atau e-wallet.",
    "FAQ1D": "Tunggu pengerjaan desain logo dan branding anda oleh tim kami. Kami akan mengirimkan konsep desain logo dan branding anda dalam waktu 1-3 hari kerja tergantung pada paket yang anda pilih.",
    "FAQ1E": "Berikan umpan balik dan revisi untuk desain logo dan branding anda hingga anda puas dengan hasil akhirnya. Anda bisa melakukan revisi gratis sesuai dengan jumlah yang ditentukan di paket yang anda pilih.",
    "FAQ1F": "Terima file akhir desain logo dan branding anda dalam format yang anda butuhkan. Anda akan mendapatkan file dalam format JPG, PNG, PDF, EPS, AI, dan SVG.",
    "FAQ2A": "Berapa Lama Proses Kerja di kanglogo.com ?",
    "FAQ2B": "Proses kerja di kanglogo.com tergantung pada paket desain yang anda pilih. Biasanya durasi pekerjaan sudah kami cantumkan pada setiap paket guna menyesuaikan jenis layanan dan jumlah desain yang akan dikerjakan. Biasanya kami akan mengirimkan konsep desain logo dan branding anda dalam waktu 1-3 hari kerja. Proses kerja di kanglogo.com dimulai setelah anda melakukan pembayaran dan mengkonfirmasinya kepada kami.",
    "FAQ3A": "Apakah bergaransi jika desain kurang sesuai ?",
    "FAQ3B": "Kami memberikan garansi 100% jika pengerjaan desain belum kami lakukan disebabkan kelalaian kami, atau kami memiliki kendala dalam pengerjaan. Kami akan mengembalikan uang anda sepenuhnya jika itu terjadi. Namun, jika desain sudah dikerjakan dan uang muka dibayarkan, kami tidak memberikan penggantian uang sepenuhnya, namun kami akan mengganti revisi sepuasnya hingga anda puas dengan hasil akhirnya. Kami berkomitmen untuk memberikan layanan desain grafis terbaik untuk anda.",
    
    "ABOUT1": "Siapakah Kami ?",
    "ABOUT2": "Kanglogo.com adalah penyedia layanan profesional dalam membuat logo, banner, icon, ilustrasi, dan desain grafis lainnya. Didirikan pada tahun 2021, kami telah melayani ribuan klien dari pasar domestik maupun internasional yang mempercayakan kami dengan kebutuhan desain logo dan branding mereka. Kami melayani berbagai jenis bisnis, mulai dari usaha mikro, kecil, dan menengah hingga situs web pribadi. Fokus kami adalah memberikan layanan berkualitas terbaik untuk memenuhi kebutuhan desain grafis anda. Kami memiliki tim yang kreatif dan berpengalaman untuk menghasilkan desain logo dan branding yang sesuai dengan identitas bisnis anda. Dengan memilih Kanglogo.com, anda akan mendapatkan layanan desain grafis terbaik untuk meningkatkan citra bisnis anda.",
    "ABOUT3": "Apa yang membuat Kanglogo.com berbeda dari penyedia layanan desain grafis lainnya? Berikut adalah beberapa alasan mengapa anda harus memilih Kanglogo.com:",
    "ABOUT4": "Kami menawarkan harga yang terjangkau dan transparan untuk setiap layanan yang kami tawarkan. Anda bisa melihat daftar harga kami di situs web kami dan memilih paket yang sesuai dengan anggaran dan kebutuhan anda.",
    "ABOUT5": "Kami menawarkan proses yang mudah dan cepat untuk mendapatkan desain logo dan branding yang anda inginkan. Anda hanya perlu mengisi brief, melakukan pembayaran, menunggu pengerjaan desain, memberikan umpan balik, dan menerima file akhir.",
    "ABOUT6": "Kami menawarkan jaminan kepuasan dan revisi gratis untuk setiap layanan yang kami tawarkan. Anda bisa memberikan umpan balik dan saran untuk meningkatkan desain logo dan branding anda hingga anda puas dengan hasil akhirnya.",
    "ABOUT7": "Kami menawarkan layanan konsultasi gratis untuk membantu anda menentukan konsep dan gaya desain logo dan branding yang sesuai dengan bisnis anda. Anda bisa menghubungi kami melalui email, telepon, atau chat online kapan saja anda membutuhkan bantuan atau saran.",
    "ABOUT8": "Kami menawarkan portofolio yang luas dan berkualitas untuk menunjukkan kemampuan dan pengalaman kami dalam bidang desain grafis. Anda bisa melihat contoh-contoh desain logo dan branding yang telah kami buat untuk klien-klien kami sebelumnya di situs web kami.",
    "ABOUT9": "Menjadi perusahaan desain yang terpercaya dan diakui oleh klien kami atas kualitas layanan dan kreativitas yang kami berikan.",
    "ABOUT10": "Menjadi perusahaan desain yang tidak sekadar menyediakan layanan desain, melainkan juga mampu memberikan dampak positif bagi perusahaan yang memanfaatkan jasa kami.",
    "ABOUT11": "Menjadi perusahaan desain di Indonesia yang berkomitmen untuk membawa perubahan yang tidak hanya bersifat layanan, tetapi juga bermanfaat bagi organisasi keagamaan, kemanusiaan, dan sosial yang memerlukan dukungan kami.",
    "ABOUT12": "Membangun hubungan yang kuat dengan klien dan mitra layanan kami untuk menumbuhkan kepercayaan dan menghasilkan karya terbaik yang mungkin.",
    "ABOUT13": "Terus meningkatkan keterampilan dan keahlian tim desain kami untuk memberikan hasil yang kreatif dan inovatif dalam setiap proyek yang kami kerjakan.",
    "ABOUT14": "Kami menggunakan perangkat lunak desain yang mudah diakses oleh klien, sehingga memudahkan mereka untuk menerima dan memodifikasi file desain yang kami berikan. Selain itu, kami berkomitmen untuk menggunakan perangkat lunak dan aset desain yang legal, tanpa terlibat dalam pembajakan atau penggunaan ilegal aset desain. Dengan demikian, kami dapat memberikan solusi desain yang aman, akurat, dan berkualitas tinggi untuk klien kami.",
    "ABOUT15": "Menciptakan lingkungan kerja yang sehat dan produktif bagi tim desain kami, dan memotivasi mereka untuk terus berkembang dan memberikan yang terbaik untuk klien kami.",
    "ABOUT16": "Kami berkomitmen untuk menjaga komitmen kami terhadap keberlanjutan dan tanggung jawab dalam setiap aspek kegiatan bisnis kami, termasuk meminimalkan dampak negatif terhadap lingkungan dan masyarakat sekitar.",
    "ABOUT17": "Target pelanggan kami adalah bisnis di kisaran UKM hingga menengah, dan individu yang mencari layanan desain logo profesional. Kami percaya bahwa dengan menyediakan layanan desain berkualitas tinggi, kami dapat membantu meningkatkan citra dan kepercayaan publik terhadap bisnis atau individu ini. Kami fokus pada memahami kebutuhan dan preferensi klien kami dengan mendengarkan secara aktif permintaan dan umpan balik mereka. Selain itu, kami memastikan bahwa desain yang kami hasilkan tidak hanya memiliki nilai estetika yang tinggi, tetapi juga merepresentasikan dengan akurat nilai dan tujuan dari bisnis atau individu yang kami layani. Kami berkomitmen untuk memberikan solusi desain yang tepat waktu, efektif, dan efisien. Kami siap berkolaborasi dengan klien kami di setiap tahap proses desain, mulai dari perencanaan dan konseptualisasi, hingga implementasi desain.",
    "ABOUT18": "Strategi kami adalah untuk menawarkan layanan desain logo yang profesional, unik, dan menarik dengan harga yang terjangkau dan kompetitif. Kami ingin menjadi pilihan utama bagi klien kami dalam memenuhi kebutuhan desain logo mereka. Kami menggunakan strategi pemasaran digital untuk menjangkau dan menarik pelanggan potensial. Kami memanfaatkan situs web, media sosial, email, dan blog untuk mempromosikan layanan kami dan menampilkan portofolio kami. Kami juga menggunakan testimoni, ulasan, dan referensi dari klien-klien kami sebelumnya untuk meningkatkan kredibilitas dan reputasi kami. Kami menggunakan strategi pelayanan pelanggan yang ramah, responsif, dan transparan untuk mempertahankan dan meningkatkan loyalitas pelanggan. Kami berusaha untuk memberikan pengalaman terbaik bagi klien kami sepanjang proses desain logo. Kami selalu siap untuk menjawab pertanyaan, memberikan saran, dan menyelesaikan masalah yang mungkin timbul. Kami juga memberikan jaminan kepuasan dan revisi gratis untuk setiap layanan yang kami tawarkan.",
    "ABOUT19": "Jenis desain yang kami gunakan Kami menggunakan berbagai jenis desain untuk menciptakan logo yang sesuai dengan identitas dan pesan bisnis atau individu yang kami layani. Jenis desain yang kami gunakan antara lain:",
    "ABOUT20": "Desain minimalis: Desain ini menggunakan elemen yang sederhana, bersih, dan fungsional untuk menciptakan logo yang mudah diingat dan elegan. Desain ini cocok untuk bisnis atau individu yang ingin menunjukkan profesionalisme, kualitas, dan kesederhanaan.",
    "ABOUT21": "Desain karakter: Desain ini menggunakan karakter, baik manusia, hewan, atau benda, untuk menciptakan logo yang menarik dan menyenangkan. Desain ini cocok untuk bisnis atau individu yang ingin menunjukkan kepribadian, kreativitas, dan keunikan.",
    "ABOUT22": "Desain elegan: Desain ini menggunakan elemen yang mewah, anggun, dan klasik untuk menciptakan logo yang berkelas dan prestisius. Desain ini cocok untuk bisnis atau individu yang ingin menunjukkan kemewahan, keanggunan, dan kecanggihan.",
    "ABOUT23": "Desain flat: Desain ini menggunakan elemen yang datar, sederhana, dan berwarna-warni untuk menciptakan logo yang modern dan dinamis. Desain ini cocok untuk bisnis atau individu yang ingin menunjukkan kekinian, inovasi, dan kesegaran.",
    "ABOUT24": "Kami juga selalu mendukung pembaruan desain yang baru yang saat ini sedang tren. Kami selalu mengikuti perkembangan dan perubahan dalam dunia desain grafis. Kami selalu berusaha untuk menghasilkan desain logo yang relevan, terkini, dan menonjol di antara pesaing.",
    "ABOUT25": "Kanglogo.com adalah pilihan terbaik untuk kebutuhan desain logo dan branding anda. Dengan Kanglogo.com, anda akan mendapatkan desain logo dan branding yang profesional, unik, dan menarik untuk mewakili bisnis anda. Segera hubungi kami dan pesan layanan kami sekarang juga!",
    "ABOUT26": "Jika anda memiliki pertanyaan seputar layanan dan informasi bisnis kami, silakan hubungi kami melalui email di kanglogokece@gmail.com. Kami akan dengan senang hati menjawab pertanyaan anda dan memberikan informasi yang anda butuhkan. Anda juga bisa mengunjungi situs web kami di www.kanglogo.com untuk melihat lebih banyak tentang layanan dan portofolio kami. Kami berharap dapat bekerja sama dengan anda dalam mewujudkan logo dan branding impian anda. Terima kasih atas minat dan kepercayaan anda kepada Kanglogo.com.",
    "TERM1": "Sebelum menggunakan layanan desain Kanglogo.com, penting bagi Anda untuk membaca dan memahami syarat dan ketentuan, prosedur pembuatan desain, dan FAQ yang ada di laman ini. Syarat dan ketentuan ini dapat berubah sewaktu-waktu tanpa pemberitahuan sebelumnya, dan dengan menggunakan layanan Kanglogo.com, Anda dianggap menyetujui dan terikat oleh perubahan tersebut. Oleh karena itu, kami sarankan Anda untuk rutin mengecek dan memahami isi dari syarat dan ketentuan ini dan setiap perubahannya. Anda bertanggung jawab untuk mengetahui dan mematuhi syarat dan ketentuan yang berlaku agar tidak terjadi masalah di kemudian hari.",
    "TERM2": "Layanan desain yang disediakan oleh Kanglogo.com menawarkan layanan desain online yang ditujukan kepada individu atau perusahaan melalui website dan media sosial tanpa perlu pertemuan tatap muka. Setelah melakukan pemesanan melalui form yang tersedia dan menyelesaikan pembayaran penuh dan konfirmasi pembayaran, klien dapat mengirimkan briefing proyek secara spesifik berupa tulisan dan gambar referensi, serta merevisi desain yang diterima.",
    "TERM3": "Kanglogo.com menyediakan berbagai layanan desain yang dijelaskan dalam setiap paket yang tercantum di brosur atau website yang dipilih, sesuai dengan prosedur yang telah ditetapkan. Perubahan spesifikasi paket desain hanya berlaku untuk pesanan setelah perubahan tersebut, dan tidak dapat diterapkan secara retrospektif.",
    "TERM4": "Standar warna yang digunakan dalam setiap proyek desain adalah RGB, kecuali klien meminta standar warna lain seperti PANTONE atau CMYK. Jika ada perubahan standar warna setelah proyek dimulai, biaya tambahan akan dikenakan. Demikian pula, meminta dua standar warna dalam hasil akhir juga akan dikenakan biaya tambahan.",
    "TERM5": "Format file yang disediakan meliputi file lunak seperti PNG/JPG dan file sumber seperti EPS/AI/CDR/PDF/PSD. Penerimaan format file disesuaikan dengan paket yang dipilih dan tidak dapat diubah dalam kondisi tertentu. Jika klien meminta atau menambahkan format file lain yang tidak tercantum dalam paket, biaya tambahan akan dikenakan.",
    "TERM6": "Klien bertanggung jawab penuh atas penulisan data briefing dan melakukan riset yang diperlukan untuk proyek desain, termasuk menyajikan hasil riset dengan jelas, konsisten, dan akurat, serta menyajikan referensi dan ilustrasi yang memadai atau gambar-gambar relevan terkait briefing yang dikirim. Data briefing harus dikirim dalam bentuk teks beserta file referensi yang memadai melalui form, pesan chat, email, atau media sosial.",
    "TERM7": "Kanglogo.com tidak bertanggung jawab atas peninjauan atau perbaikan isi dari briefing yang dikirim. Jika ada perubahan data briefing, perubahan harus dilakukan dengan cara yang sama saat pengiriman briefing dan sebelum proses desain dimulai.",
    "TERM8": "Kami tidak dapat menerima briefing yang disampaikan secara lisan atau dalam media yang mudah terhapus, karena dianggap tidak dikirim atau tidak diterima oleh kami sebagai penyedia layanan.",
    "TERM9": "Perubahan data briefing setelah proses pengerjaan dianggap sebagai revisi. Jumlah revisi yang diizinkan akan disesuaikan dengan paket yang dipilih dan revisi tambahan akan dikenakan biaya tambahan. Kami menyarankan klien untuk memetakan perubahan dan mengumpulkan semua perubahan dalam satu revisi untuk mengurangi revisi yang berlebihan.",
    "TERM10": "Kami akan menghitung biaya revisi berdasarkan perubahan yang diminta. Jika ada kesalahan dalam pengiriman briefing, revisi akan dianggap sebagai perubahan dan akan dikurangi sesuai dengan jumlah perubahan yang diminta.",
    "TERM11": "Kami juga ingin mengingatkan bahwa revisi akan dihentikan jika melebihi batas normal yang disediakan dalam paket yang dipilih, sehingga kami menyarankan klien untuk mempertimbangkan dengan baik sebelum meminta revisi tambahan.",
    "TERM12": "Untuk menghindari revisi berulang dan menjamin kepuasan pelanggan, setelah revisi selesai, kami meminta briefing tambahan dan referensi sebagai acuan utama untuk memahami jenis dan preferensi desain logo yang diinginkan. Jika Anda tidak dapat memberikan briefing dalam waktu 3 hari setelah revisi selesai, maka kami tidak dapat melanjutkan pengerjaan dan tidak dapat memberikan pengembalian dana. Oleh karena itu, kami sangat menyarankan Anda untuk memberikan briefing yang jelas dan tepat waktu agar proyek dapat diselesaikan dengan sukses.",
    "TERM13": "Kanglogo.com berkomitmen untuk memberikan respons, komunikasi, dan fleksibilitas yang cepat, tepat waktu, dan fleksibel kepada klien kami. Kami siap merespons dan menjawab pertanyaan Anda sebelum dan selama proses desain. Kami meminta klien kami untuk juga merespons setiap pesan atau pertanyaan yang kami ajukan, terutama mengenai data briefing yang diperlukan untuk memulai proses desain.",
    "TERM14": "Kami sangat menyarankan klien untuk merespons setiap pesan yang kami kirimkan untuk menghindari kesalahpahaman dan kurangnya informasi yang diperlukan untuk menyelesaikan desain dengan baik. Kami akan memperhatikan setiap respons dan pertanyaan yang Anda ajukan, dan akan mengambil tindakan yang diperlukan untuk memastikan bahwa desain yang kami kirimkan sesuai dengan kebutuhan dan keinginan Anda.",
    "TERM15": "Namun, jika klien tidak merespons pesan atau pertanyaan kami dalam jangka waktu yang ditentukan, kami tidak bertanggung jawab atas kesalahan dalam hasil desain akibat kurangnya atau kesalahan dalam briefing desain yang kami terima. Kami meminta klien untuk memperhatikan setiap pesan dan pertanyaan yang kami ajukan untuk menghindari kesalahan.",
    "TERM16": "Jika kami tidak menerima respons dari klien dalam jangka waktu tertentu setelah mengirimkan hasil desain, kami akan menunda pengerjaan selama 1 minggu. Jika setelah 1 minggu tidak ada respons dari klien, kami akan mengirimkan format file sesuai dengan paket yang dipesan dan pengerjaan dianggap selesai. Kami mengharapkan kerjasama dan komunikasi yang baik dari klien agar kami dapat memberikan hasil desain yang memuaskan.",
    "TERM17": "Kami menawarkan opsi untuk meningkatkan paket layanan yang telah dipesan oleh klien, baik itu pada tahap pra-desain atau setelah proses desain selesai. Kami memberikan fleksibilitas dalam jangka waktu dua minggu setelah file hasil desain telah dikirimkan kepada klien. Selama periode ini, klien dapat meningkatkan paket layanan sesuai dengan kebutuhan yang muncul. Kami siap memberikan saran dan bimbingan kepada klien mengenai opsi upgrade yang tersedia. Namun, setelah periode dua minggu berakhir, kami tidak dapat menerima permintaan untuk meningkatkan paket layanan.",
    "TERM18": "Kami memiliki jangka waktu penyelesaian proyek standar yang tercantum di setiap paket layanan yang kami tawarkan. Kami berkomitmen untuk menyelesaikan proyek dalam jangka waktu yang ditentukan, yaitu 3 hari kerja (4 hari jika hari kerja bertepatan dengan hari libur atau hari raya) setelah pembayaran dan pengiriman briefing. Kami mengharapkan respons yang cepat dan tepat waktu dari klien mengenai hasil desain yang kami kirimkan, agar pengerjaan dapat selesai tepat waktu.",
    "TERM19": "Jika klien tidak merespons hasil desain yang kami kirimkan dalam waktu 14 hari setelah pengiriman, maka pada hari ke-15 kami akan mengirimkan hasil desain tanpa ada tinjauan dari klien. Dalam hal ini, kerjasama antara Kanglogo.com dan klien dianggap selesai dan kami tidak lagi memiliki kewajiban untuk mengerjakan proyek. Kami juga tidak akan melakukan pengembalian dana atas pembayaran yang dilakukan oleh klien, tanpa terkecuali.",
    "TERM20": "Klien memiliki hak penuh atas hasil akhir dari satu desain yang kami buat. Namun, klien tidak memiliki hak atas semua revisi dan/atau konsep awal, serta produk turunannya. Oleh karena itu, klien tidak diperbolehkan meneruskan, menampilkan, atau mempublikasikan revisi dan/atau konsep awal kepada pihak manapun, dimanapun, dan melalui media apapun.",
    "TERM21": "Kami perlu menekankan bahwa jika klien melanggar ketentuan ini, Kanglogo.com Studio berhak menghentikan segala jenis layanan atau produk yang kami berikan kepada klien tanpa ada kompensasi dalam bentuk apapun. Kami sangat berharap bahwa klien dapat menghormati hak cipta dan privasi kami, sebagaimana kami menghormati klien sebagai pelanggan kami.",
    "TERM22": "Kami menjamin bahwa desain yang kami buat adalah asli dan kami dapat membuktikannya melalui sketsa atau karya kami di atas kertas. Setelah desain disetujui atau dibeli oleh klien, hak cipta dan hak paten atas desain akan sepenuhnya dimiliki oleh klien. Namun, perlu dicatat bahwa desain yang menjadi hak cipta klien adalah desain akhir yang telah disetujui, baik telah direvisi atau tidak. Desain awal atau desain yang tidak dipilih oleh klien akan tetap menjadi milik kami dan kami berhak menjual atau menggunakan kembali sebagai aset kami. Setelah penyerahan desain dan dokumen lisensi kepada klien, klien akan menjadi pemilik resmi hak cipta dan hak paten atas desain yang disetujui atau dibeli.",
    "TERM23": "Kanglogo.com memiliki hak penuh untuk menggunakan desain akhir yang telah disetujui oleh klien sebagai sarana promosi di website portofolio dan media sosial kami tanpa biaya tambahan atau royalti (royalty-free) dengan batas waktu penggunaan yang tidak terbatas.",
    "TERM24": "Jika klien menggunakan layanan paket non-file sumber dan ingin menggunakan desain untuk media cetak, klien harus membeli file sumber dengan harga sebagai berikut: Rp 250.000 untuk file Ai atau CDR, Rp 300.000 untuk file PSD, dan Rp 500.000 untuk file sumber ganda seperti AI, CDR, PSD, PDF, EPS, dan SVG.",
    "TERM25": "Kami ingin menginformasikan kepada Anda bahwa sebagai klien, Anda memiliki hak cipta atas desain yang disetujui atau dibeli, dan Anda dapat menggunakannya untuk tujuan komersial atau penyebaran sesuai keinginan Anda. Namun, Anda harus mematuhi aturan hak cipta dan tidak melakukan tindakan pelanggaran seperti memvektorkan file lunak desain di layanan lain tanpa izin dari pemilik hak cipta.",
    "TERM26": "Jika ada pelanggaran hak cipta atau penggunaan tidak sah atas desain tersebut, kami akan mengambil tindakan hukum yang diperlukan untuk menegakkan hak cipta kami atau klien sebagai pemilik desain tersebut. Sebagai penyedia layanan desain, kami menghargai hak cipta dan melarang segala bentuk pelanggarannya.",
    "TERM27": "Untuk setiap transaksi dengan jumlah di bawah Rp 300.000 (Tiga Ratus Ribu Rupiah), klien diwajibkan melakukan pembayaran penuh sebelum proyek dapat dimulai.",
    "TERM28": "Sebagai standar prosedur pembayaran, kami mewajibkan klien untuk melakukan pembayaran uang muka sebesar 40% apabila total nominal transaksi di atas Rp 301.000 sebelum memulai pengerjaan proyek.",
    "TERM29": "Jika klien tidak puas dengan konsep awal yang kami berikan dan belum meminta revisi, mereka dapat meminta pengembalian dana atas pembayaran yang dilakukan. Namun, ini hanya berlaku untuk transaksi yang belum dibayar penuh. Jika biaya layanan dibayar tunai, pengembalian dana sebesar 70% dari jumlah transaksi akan diberikan. Sementara itu, jika biaya layanan dibayar sebagai uang muka, pengembalian dana sebesar 60% dari jumlah transaksi akan diberikan. Namun, klien tidak berhak mendapatkan pengembalian dana jika mereka telah meminta revisi atau gagal merespons dalam jangka waktu yang ditentukan.",
    "TERM30": "Untuk menandai dimulainya proses pengerjaan layanan, klien diwajibkan untuk mengonfirmasi pembayaran dengan mengirimkan foto bukti pembayaran atau screenshot sebagai bukti pembayaran. Kami akan mengunggah screenshot ini sebagai testimoni dari klien di media sosial atau website kami. Untuk menjaga privasi klien, nama dan nomor rekening akan disamarkan.",
    "PRIV": "Kami sangat menghormati privasi pengguna kami dan berusaha keras untuk menjaga informasi pribadi yang mereka berikan kepada kami melalui layanan kami. Kebijakan privasi ini menjelaskan bagaimana kami mengumpulkan, memanfaatkan, dan menjaga informasi pribadi pengguna kami.",
    "PRIV": "Kami mengumpulkan informasi yang Anda sampaikan kepada kami saat Anda menggunakan layanan kami, seperti nama lengkap, alamat email, nomor telepon, dan informasi pembayaran.",
    "PRIV": "Kami memanfaatkan informasi pribadi yang kami kumpulkan untuk tujuan tertentu, seperti menyelesaikan pesanan, mengirim email terkait pesanan, dan memberikan dukungan pelanggan. Kami juga dapat memanfaatkan informasi ini untuk mengirimkan promosi dan penawaran spesial yang berkaitan dengan layanan kami, tetapi Anda selalu dapat memilih untuk tidak menerima email tersebut.",
    "PRIV": "Kami mengambil langkah-langkah keamanan yang tepat untuk menjaga informasi pribadi Anda dari akses atau penggunaan yang tidak sah. Kami juga menggunakan enkripsi SSL untuk menjaga informasi pribadi Anda saat ditransmisikan melalui internet.",
    "PRIV": "Kami tidak menjual, memperdagangkan, atau menyewakan informasi pribadi pengguna kami kepada pihak ketiga. Namun, kami dapat membagikan informasi Anda dengan pihak ketiga jika diperlukan untuk menyelesaikan pembayaran atau untuk mematuhi undang-undang atau proses hukum yang berlaku.",
    "PRIV": "Anda dapat meminta akses ke informasi pribadi Anda yang kami simpan atau memperbarui informasi tersebut dengan menghubungi kami melalui email atau nomor telepon yang tercantum di bawah ini.",
    "PRIV": "Ya, kami menggunakan cookie untuk melacak preferensi pengguna dan untuk meningkatkan pengalaman pengguna di situs web kami.",
    "PRIV": "Kebijakan ini dapat berubah dari waktu ke waktu. Setiap perubahan pada kebijakan ini akan diposting di situs web kami. Jika Anda memiliki pertanyaan atau komentar tentang kebijakan privasi kami, silakan hubungi kami melalui email di kanglogokece@gmail.com atau melalui telepon di +62 818-145-012.",
    "PROG": "Proses Desain: Dari Awal hingga Akhir",
    "PROG": "Kami memiliki proses desain yang profesional dan kreatif, yang terdiri dari tujuh langkah yang berbeda, mulai dari briefing klien hingga panduan pengiriman dan branding.",
    "PROG": "Proses desainmeliputi tujuh langkah yang sistematis dan terstruktur",
    "PROG": "Mulai dari briefing klien hingga panduan pengiriman dan branding. Kami berkomunikasi, berkolaborasi, dan berinovasi untuk memberikan solusi desain logo yang terbaik bagi bisnis Anda.",
    "PROG": "Briefing Klien",
    "PROG": "Kami berkomunikasi dengan klien untuk memahami kebutuhan, tujuan, dan harapan mereka. Kami juga mengumpulkan informasi tentang bisnis, target pasar, pesaing, dan preferensi gaya mereka.",
    "PROG": "Penelitian dan Inspirasi",
    "PROG": "Kami melakukan penelitian tentang industri, tren, dan contoh desain yang relevan dengan proyek desain. kami juga mencari inspirasi dari sumber-sumber kreatif seperti seni, budaya, atau alam.",
    "PROG": "Pengembangan Konsep",
    "PROG": "Kami mulai mengembangkan konsep desain berdasarkan hasil briefing dan penelitian. Kami membuat sketsa, mood board, atau mockup untuk mengeksplorasi ide-ide desain secara visual.",
    "PROG": "Penyempurnaan Desain",
    "PROG": "Kami memilih konsep desain terbaik dan mulai menyempurnakannya. Kami memperhatikan detail, warna, tipografi, dan elemen lainnya yang mempengaruhi estetika dan fungsi desain tersebut.",
    "PROG": "Presentasi",
    "PROG": "Kami mempresentasikan desain kepada klien dan menjelaskan alasan dan proses di baliknya. Kami juga mendapatkan umpan balik dari klien dan mengevaluasi kekuatan dan kelemahan desain.",
    "PROG": "Revisi dan Persetujuan",
    "PROG": "Kami melakukan revisi desain sesuai dengan umpan balik klien. Kami juga memastikan bahwa desain memenuhi standar kualitas dan spesifikasi teknis yang dibutuhkan. Kami mendapatkan persetujuan akhir dari klien sebelum melanjutkan ke langkah terakhir.",
    "PROG": "Panduan Pengiriman dan Branding",
    "PROG": "Kami menyiapkan dan mengirimkan file desain kepada klien dalam format yang sesuai. Kami juga memberikan panduan penggunaan dan branding untuk desain agar klien dapat menggunakannya dengan benar dan konsisten",
    "ORIG": "Original Design",
    "CUSTCOL": "Customized color",
    "CUSTEXT": "Customized text",
    "EDMF": "Editable Master Files",
    "LCNS": "Use License",
    "ATCRT": "Add To Cart",
    "ORDR": "Order Now",
    "DESCRP": "Description",
    
    "JUDULKLIEN": "Klien Terbaik Kami",
    "DESCKLIEN1": "Di sini Anda dapat melihat klien terbaik kami yang berasal dari berbagai bidang dan sektor. Kami selalu berusaha memberikan layanan yang terbaik, tepat, dan memuaskan bagi mereka.",
    "DESCKLIEN2": "Kami bangga memiliki klien terbaik yang telah memilih jasa desain logo kami.",
    "JUDULTSTMN": "Testimoni Pelanggan",
    "DESCTSTMN1": "Kami bangga dengan hasil kerja kami dan kami senang melihat pelanggan kami puas dengan jasa desain logo kami.",
    "DESCTSTMN2": "Apa kata pelanggan kami tentang jasa desain logo kami?",
    "JUDULLOGOBRN": "Tarif Desain Logo Personal Brand",
    "DESCLOGOBRN": "Adalah layanan jasa desain logo profesional yang diperuntukan bagi personal branding yang ingin meningkatkan brandingnya",
    "JUDULLOGOCOM": "Tarif Desain Logo Perusahaan",
    "DESCLOGOCOM": "Adalah layanan jasa desain logo profesional untuk perusahaan, baik itu perusahaan skala kecil ataupun skala besar.",
    "JUDULLOGODGT": "Tarif Desain Logo Digital & StartUp",
    "DESCLOGODGT": "Adalah layanan jasa desain logo profesional yang diperuntukan startup, perusahaan digital, toko online, ecourse, ecomerce dan lainnya.",
    "JUDULLOGOBLG": "Tarif Desain Logo Blog",
    "DESCLOGOBLG": "Adalah layanan jasa desain logo profesional yang diperuntukan pada pengguna blog, baik itu personal blog, blog news dan lainnya.",
    "JUDULLOGOEVN": "Tarif Desain Logo Event atau organisasi",
    "DESCLOGOEVN": "Adalah layanan jasa desain logo profesional yang diperuntukan untuk sebuah simbol acara, ulang tahun, memperingati dan lainnya.",
    "JUDULLOGOESP": "Tarif Desain Logo Esport",
    "DESCLOGOESP": "Adalah layanan jasa desain logo profesional yang diperuntukan para streamer pemula atau profesional",
    "JUDULLOGOUMK": "Tarif Desain Logo UMKM",
    "DESCLOGOUMK": "Adalah layanan jasa desain logo profesional yang diperuntukan bagi para pelaku usaha UMKM",
    
    "100": "Rp 100.000",
    "150": "Rp 150.000",
    "200": "Rp 200.000",
    "250": "Rp 250.000",
    "350": "Rp 350.000",
    "450": "Rp 450.000",
    "550": "Rp 550.000",
    "650": "Rp 650.000",
    "700": "Rp 700.000",
    "800": "Rp 800.000",
    "850": "Rp 850.000",
    "950": "Rp 950.000",
    "1250": "Rp 1.250.000",
    "2650": "Rp 2.650.000",
    "4850": "Rp 4.850.000",
    "8850": "Rp 8.550.000",
    "FREE": "Rp 0 (GRATIS)"
  }
    };



 $(document).ready(function () {
      var lang = localStorage.getItem('lang') || 'en-gb';
      $(".lang").each(function (index, element) {
        $(this).text(arrLang[lang][$(this).attr("key")]);
      });

      $(".translate").click(function () {
        var lang = $(this).attr("id");
        localStorage.setItem('lang', lang);

        $(".lang").each(function (index, element) {
          $(this).text(arrLang[lang][$(this).attr("key")]);
        });
      });
    });
