
var arrLang = {
  "en-gb": {
    "HOME": "Home",
    "FEATURE": "Feature",
    "HOW": "How We Work",
    "FAQ": "Faq",
    "PRICELIST": "price list",
    
    "TITLEH": "Bringing Your Vision to Life Through Logo Design",
    "DESCH": "Enhance your brand identity with a professional logo design. We are here to improve your business identity with a quality logo that suits your business needs.",
    
    "OPTION": "Logo Options",
    "FILOSOP": "Logo Philosophy",
    "LOGOS": "Derived Logo",
    "MAJOR": "Major Revision",
    "MINOR": "Minor Revisions",
    "UNLI": "Unlimited",
    "BGUID": "Branding Guidelines",
    "BMATER": "Branding Materials",
    "PKG": "Packaging Design",
    "STN": "Stationary Design",
    "MSS": "Social Media Design",
    "JSY": "Jersey Design",
    "MERCH": "Merchandise Design",
    "BCRD": "Business Card Design",
    "TWTCH": "Twitch Design Set",
    "YTUB": "Youtube Design Set",
    "FBSET": "Facebook Design Set",
    "TWTER": "Twitter Design Set",
    "FREEMOCK": "Free MockUp",
    "MASTER": "Master Files",
    "PAY": "Receive payment",
    "CTH": "Design Example",
    "CTHDESC": "The following is an example of what we have worked on.",
    
    "LOGOBRAN": "Personal Brand Logo",
    "LOGOCOMP": "Company Logo",
    "LOGOBLOG": "Blogger Logo",
    "LOGOSTAR": "StartUp Logo",
    "LOGOUMKM": "MSME Logo",
    "LOGOESPORT": "Esport Logo",
    "LOGOFREE": "Free Logo",
    
    "LINK": "Link",
    "SHOP": "Shop",
    "PORTO": "Portfolio",
    "TESTI": "Testimonials",
    "CLIENT": "Our Client",
    "SERVI": "Service",
    
    "SUPP": "Support",
    "ABOUT": "About",
    "TERM": "Terms and conditions",
    "PRIV": "Privacy Policy",
    "PROG": "Work Process",
    "HUB": "Reach Us",
    
    "JUDULLOGOBRN": "Tarif Desain Logo Personal Brand",
    "DESCLOGOBRN": "Adalah layanan jasa desain logo profesional yang diperuntukan bagi personal branding yang ingin meningkatkan brandingnya",
    
    "JUDULLOGOCOM": "Tarif Desain Logo Perusahaan",
    "DESCLOGOCOM": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    
    "JUDULLOGODGT": "Tarif Desain Logo Digital & StartUp",
    "DESCLOGODGT": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    
    "100": "USD 7$",
    "150": "USD 10$",
    "200": "USD 12$",
    "250": "USD 15$",
    "350": "USD 25$",
    "450": "USD 30$",
    "550": "USD 35$",
    "650": "USD 40",
    "700": "USD 45$",
    "800": "USD 50$",
    "850": "USD 55$",
    "950": "USD 65$",
    "1250": "USD 85$",
    "2650": "USD 170$",
    "4850": "USD 350$",
    "8850": "USD 550$",
    "FREE": "USD 0$ (FREE)"
  },

  "zh-tw": {
    "HOME": "Beranda",
    "FEATURE": "Fitur",
    "HOW": "Bagaimana Cara Kerja Kami",
    "FAQ": "Faq",
    "PRICELIST": "Daftar Harga",
    
    "TITLEH": "Mewujudkan Visi Anda Melalui Desain Logo",
    "DESCH": "Tingkatkan identitas merek Anda dengan desain logo profesional. Kami hadir untuk meningkatkan identitas bisnis Anda dengan logo berkualitas dan sesuai kebutuhan bisnis anda.",
    
    "OPTION": "Opsi Logo",
    "FILOSOP": "Filosopi Logo",
    "LOGOS": "Logo Turunan",
    "MAJOR": "Revisi Besar",
    "MINOR": "Revisi Kecil",
    "UNLI": "Tidak Terbatas",
    "BGUID": "Pedoman Branding",
    "BMATER": "Material Branding",
    "PKG": "Desain Packaging",
    "STN": "Desain Stationary",
    "MSS": "Desain Media Sosial",
    "JSY": "Desain Jersey",
    "MERCH": "Desain Merchandise",
    "BCRD": "Desain Kartu Nama",
    "TWTCH": "Set Desain Twitch",
    "YTUB": "Set Desain Youtube",
    "FBSET": "Set Desain Facebook",
    "TWTER": "Set Desain Twitter",
    "FREEMOCK": "Gratis MockUp",
    "MASTER": "File Master",
    "PAY": "Menerima pembayaran",
    "CTH": "Contoh Desain",
    "CTHDESC": "Berikut ini adalah contoh yang telah kami kerjakan.",
    
    "LOGOBRAN": "Logo Personal Brand",
    "LOGOCOMP": "Logo Perusahaan",
    "LOGOBLOG": "Logo Blogger",
    "LOGOSTAR": "Logo StartUp",
    "LOGOUMKM": "Logo UMKM",
    "LOGOESPORT": "Logo Esport",
    "LOGOFREE": "Logo Gratis",
    "LOGOFREE": "Desain Logo",
    
    "LINK": "Tautan",
    "SHOP": "Toko",
    "PORTO": "Portofolio",
    "TESTI": "Testimonials",
    "CLIENT": "Klien Kami",
    "SERVI": "Layanan",
    
    "SUPP": "Support",
    "ABOUT": "Tentang",
    "TERM": "Syarat Ketentuan",
    "PRIV": "Kebijakan pribadi",
    "PROG": "Proses Pengerjaan",
    "HUB": "Jangkau Kami",
    
    "HUB": "Pesan Sekarang",
    "HUB": "Logo Anda",
    "HUB": "Atau Beli Saja",
    "HUB": "Logo Siap Pakai",
    "HUB": "Mengapa",
    "HUB": "Kami Harus Menjadi Pilihan Pertama Anda untuk Desain Logo",
    "HUB": "Layanan desain logo kami didedikasikan untuk membuka potensi penuh merek Anda.",
    "HUB": "Desain Orisinil",
    "HUB": "Logo unik yang dirancang dengan teliti untuk membuat bisnis Anda lebih berbeda",
    "HUB": "Proses Cepat",
    "HUB": "Kami berkomitmen untuk memberikan kualitas terbaik dengan waktu yang efisien",
    "HUB": "Respon Cepat",
    "HUB": "Anda bisa mengandalkan kami, kami siap membantu Anda 24 jam",
    "HUB": "Tepat Waktu",
    "HUB": "Kami menjamin desain Anda selesai tepat waktu, tanpa mengurangi kualitas dan kreativitas.",
    "HUB": "Start Building Your Branding Now",
    "HUB": "Branding hanya dibuat sekali, namun keuntungannya lebih dari berkali-kali",
    "HUB": "Jumlah Proyek",
    "HUB": "Klien yang Bahagia",
    "HUB": "Harus Menggunakan Jasa Desain Logo Profesional",
    "HUB": "Membuat logo yang baik tidaklah mudah. Anda membutuhkan bantuan dari jasa desain logo profesional. Berikut adalah 5 alasan kenapa Anda harus menggunakan jasa desain logo profesional:",
    "HUB": "Mendapatkan Logo yang Unik dan Sesuai dengan Bisnis Anda",
    "HUB": "Jasa desain logo profesional akan melakukan riset tentang pasar, kompetitor, dan target audiens Anda sebelum membuat logo yang dapat menonjolkan keunggulan dan nilai bisnis Anda",
    "HUB": "Mendapatkan Logo yang Mudah Diingat",
    "HUB": "Jasa desain logo profesional akan membuat logo yang sederhana, jelas, dan konsisten, sehingga dapat meningkatkan awareness dan loyalitas pelanggan Anda",
    "HUB": "Dapat Meningkatkan Kredibilitas Bisnis Anda",
    "HUB": "Jasa desain logo profesional akan membuat logo yang berkualitas tinggi, rapi, dan sesuai dengan standar industri, sehingga Anda dapat menunjukkan bahwa Anda serius dan kompeten dalam bisnis Anda",
    "HUB": "Sesuai dengan Anggaran dan Waktu Anda",
    "HUB": "Jasa desain logo profesional akan menawarkan Anda paket harga yang terjangkau dan kompetitif, serta menyelesaikan logo Anda sesuai dengan deadline yang Anda tentukan, sehingga Anda dapat menghemat biaya dan waktu Anda",
    "HUB": "Tarif",
    "HUB": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    "HUB": "Pekerjaan Terakhir",
    "HUB": "Terus dapatkan informasi terbaru tentang karya terbaru kami yang menampilkan gaya dan kemampuan desain kami saat ini.",
    "HUB": "Sering",
    "HUB": "diajukan saat bertanya",
    "HUB": "Bagaimana cara memesan jasa di Kanglogo.com ?",
    "HUB": "Kunjungi situs web kami di www.kanglogo.com dan pilih paket layanan yang anda inginkan. Atau anda bisa juga melakukan pemesanan melalui whatsapp.",
    "HUB": "Isi brief desain logo dan branding anda dengan lengkap dan jelas. Anda bisa memberikan informasi tentang nama bisnis, slogan, warna, gaya, target pasar, pesaing, dan preferensi anda.",
    "HUB": "Lakukan pembayaran melalui metode yang tersedia di situs web kami. Anda bisa menggunakan transfer bank, kartu kredit, atau e-wallet.",
    "HUB": "Tunggu pengerjaan desain logo dan branding anda oleh tim kami. Kami akan mengirimkan konsep desain logo dan branding anda dalam waktu 1-3 hari kerja tergantung pada paket yang anda pilih.",
    "HUB": "Berikan umpan balik dan revisi untuk desain logo dan branding anda hingga anda puas dengan hasil akhirnya. Anda bisa melakukan revisi gratis sesuai dengan jumlah yang ditentukan di paket yang anda pilih.",
    "HUB": "Terima file akhir desain logo dan branding anda dalam format yang anda butuhkan. Anda akan mendapatkan file dalam format JPG, PNG, PDF, EPS, AI, dan SVG.",
    "HUB": "Berapa Lama Proses Kerja di kanglogo.com ?",
    "HUB": "Proses kerja di kanglogo.com tergantung pada paket desain yang anda pilih. Biasanya durasi pekerjaan sudah kami cantumkan pada setiap paket guna menyesuaikan jenis layanan dan jumlah desain yang akan dikerjakan. Biasanya kami akan mengirimkan konsep desain logo dan branding anda dalam waktu 1-3 hari kerja. Proses kerja di kanglogo.com dimulai setelah anda melakukan pembayaran dan mengkonfirmasinya kepada kami.",
    "HUB": "Apakah bergaransi jika desain kurang sesuai ?",
    "HUB": "Kami memberikan garansi 100% jika pengerjaan desain belum kami lakukan disebabkan kelalaian kami, atau kami memiliki kendala dalam pengerjaan. Kami akan mengembalikan uang anda sepenuhnya jika itu terjadi. Namun, jika desain sudah dikerjakan dan uang muka dibayarkan, kami tidak memberikan penggantian uang sepenuhnya, namun kami akan mengganti revisi sepuasnya hingga anda puas dengan hasil akhirnya. Kami berkomitmen untuk memberikan layanan desain grafis terbaik untuk anda.",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    "HUB": "Pesan",
    
    "JUDULLOGOBRN": "Tarif Desain Logo Personal Brand",
    "DESCLOGOBRN": "Adalah layanan jasa desain logo profesional yang diperuntukan bagi personal branding yang ingin meningkatkan brandingnya",
    
    "JUDULLOGOCOM": "Tarif Desain Logo Perusahaan",
    "DESCLOGOCOM": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    
    "JUDULLOGODGT": "Tarif Desain Logo Digital & StartUp",
    "DESCLOGODGT": "Kami menawarkan berbagai pilihan harga yang fleksibel dan terjangkau. Dapatkan juga tawaran spesial yang memberikan Anda nilai lebih.",
    
    "100": "Rp 100.000",
    "150": "Rp 150.000",
    "200": "Rp 200.000",
    "250": "Rp 250.000",
    "350": "Rp 350.000",
    "450": "Rp 450.000",
    "550": "Rp 550.000",
    "650": "Rp 650.000",
    "700": "Rp 700.000",
    "800": "Rp 800.000",
    "850": "Rp 850.000",
    "950": "Rp 950.000",
    "1250": "Rp 1.250.000",
    "2650": "Rp 2.650.000",
    "4850": "Rp 4.850.000",
    "8850": "Rp 8.550.000",
    "FREE": "Rp 0 (GRATIS)"
  }
    };



 $(document).ready(function () {
      var lang = localStorage.getItem('lang') || 'en-gb';
      $(".lang").each(function (index, element) {
        $(this).text(arrLang[lang][$(this).attr("key")]);
      });

      $(".translate").click(function () {
        var lang = $(this).attr("id");
        localStorage.setItem('lang', lang);

        $(".lang").each(function (index, element) {
          $(this).text(arrLang[lang][$(this).attr("key")]);
        });
      });
    });
